package com.example.finance.googlesheetsexample;

import android.content.Intent;
import android.os.Bundle;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.widget.ListView;
import android.widget.TextView;

import com.example.finance.googlesheetsexample.androidlabs.gsheets1.MyArrayAdapter;
import com.example.finance.googlesheetsexample.androidlabs.gsheets1.MyDataModel;
import com.facebook.drawee.backends.pipeline.Fresco;

import java.util.ArrayList;

public class WACCDetailedPageOne extends AppCompatActivity {

    private ListView listView;
    private ArrayList<MyDataModel> list;
    private MyArrayAdapter adapter;
    private DrawerLayout mDrawerLayout;
    private TextView textView;
    private TextView WACCDescription;
    private TextView FCFFDescription;
    private TextView CostOfCapitalDescription;
    private TextView TerminalValueDescription;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.waccdetailedpageone);

        Fresco.initialize(this);

        //!!!!!!!!!!!!!FORMAT THIS EVENTUALLY!!!!!!!!!!!!!!!!!!!!!
        //Below is repeat code from the MainPage, MainPage and Userlist use
        //the same code as below, see if there is a way to condense this

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        ActionBar actionbar = getSupportActionBar();
        //actionbar.setDisplayHomeAsUpEnabled(true);
        //actionbar.setHomeAsUpIndicator(R.drawable.baseline_menu_black_18dp);

        mDrawerLayout = findViewById(R.id.drawer_layout);

        textView = (TextView) this.findViewById(R.id.WACCTextView);


        WACCDescription = (TextView) this.findViewById(R.id.WACCDescription);
        WACCDescription.setText("What is WACC Method of Valuation?");

        WACCDescription.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(WACCDetailedPageOne.this, pdf_viewer.class));
                //Logic

            }

        });

        FCFFDescription = (TextView) this.findViewById(R.id.FCFFDescription);
        FCFFDescription.setText("What is Free Cash Flow to Firm (FCFF)?");

        FCFFDescription.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                PopUpWindow popUpWindow = new PopUpWindow();
                //TODO: look into setting text like above way
                Intent intent = new Intent(WACCDetailedPageOne.this, PopUpWindow.class);
                intent.putExtra("message", "FCFF is free cash flow to the firm.  It is" +
                        " the cash flow generated by the firm's operating assets," +
                        "net of taxes, after reinvestment needs have been met.  It is " +
                        "derived using the principle that we should focus on the money " +
                        "that actually comes into and goes out of the firm, without " +
                        "reflecting the effects of debt financing.  It is defined as:" +
                        "\n\nFCFF = EBITx(1-t) + Depreciation - ∆NWC - Capex" +
                        "\n\nwhere EBIT is operating income, t is the tax rate, Depreciation " +
                        "is the non-cash charge that is added back, ∆NWC is change in operating " +
                        "net working capital (i.e., change in non-cash current assets minus " +
                        "change in non-debt current liabilities), and Capex is Capital " +
                        "Expenditure." +
                        "\n\nWe can think of Capex-Depreciation+∆NWC as the firm's net " +
                        "reinvestment needs." +
                        "\n\nSimply put, if FCFF is a positive number, it is the total cash " +
                        "flow that is available to service debt payments and cash flows " +
                        "to equity, including dividends and stock buybacks.  If " +
                        "negative, it represents new capital that has to be raised by the " +
                        "firm from either debt or equity.");

                //



                startActivity(intent);

            }

        });

        CostOfCapitalDescription = (TextView) this.findViewById(R.id.CostOfCapitalDescription);
        CostOfCapitalDescription.setText("What is Cost of Capital?");

        //TODO: Get subscripts to work properly
        CostOfCapitalDescription.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                //Logic
                Intent intent = new Intent(WACCDetailedPageOne.this, PopUpWindow.class);
                intent.putExtra("message", "WACC is 'weighted average cost of capital.'" +
                        "It captures the idea that we must provide a 'fair' rate of return " +
                        "to each type of investor in our business, weighted by the proportion " +
                        "in which they are supplying its capital.  This rate is determined by the " +
                        "return on risk-equivalent assets - the notion is that, when investors " +
                        "give us their money, they are foregoing the opportunity to earn a " +
                        "risk-equivalent rate of return elsewhere; i.e., they are incurring " +
                        "an opportunity cost to the use of their capital." +
                        "\n\nCapital is of two types: owners' money (Equity, E) or borrowed money " +
                        "(Debt, D). If E expects a return rE, and D expects rD, and " +
                        "'f' is the tax rate, then WACC is defined as: " +
                        "\n\nWACC = rE x (E/(D+E)) + rD X (1-t) x (D/(D+E)) " +
                        "\n\nWe multiply rD by (1-t) to reflect the fact that tax laws " +
                        "allow for interest payments to debtholders to be deducted as a cost of " +
                        "doing business (while divdend payments to equityholders, with " +
                        "occasional exceptions, are not).  As a result, the true cost of " +
                        "borrowing is not all of rD, but the after-tax rD.  This provision" +
                        "in the tax laws is said to provide a 'tax shield benefit' to " +
                        "the company.");

                //



                startActivity(intent);


            }

        });

        TerminalValueDescription = (TextView) this.findViewById(R.id.TerminalValueDescription);
        TerminalValueDescription.setText("What is Terminal Value?");

        TerminalValueDescription
                .setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                //Logic
                Intent intent = new Intent(WACCDetailedPageOne.this, PopUpWindow.class);
                intent.putExtra("message", "Terminal Value (TV) is the " +
                        "continuing value of the business after the detailed forecast (or, 'proforma' " +
                        ") period ends.  It is calculated using the constant growth model: " +
                        "\n\nTV = FCFFr + (WACCr - g)," +
                        "\n\nwhere FCFFr is the cash flow in the first period after the forecast " +
                        "period ends (if the forecast period is seven years, this year 8), WACCr " +
                        "is the cost of capital in perpetuity after the forecast period, and " +
                        "g is the Terminal Growth Rate (the growth rate in free cash flow in " +
                        "perpetuity)." +
                        "\n\n The enterprise value, EV, is the present value of TV plus the " +
                        "present value of cash flows for each year of the proforma period. " +
                        "\n\n Some analysts use multiples (e.g., EV/EBITDA, EV/Sales) " +
                        "to estimate TV. However, g is implicit (and therefore, hidden) " +
                        "in a multiple, while iti s made explicit in the constant growth model. " +
                        "Moreover, the danger with using multiples is that they undercut " +
                        "the very notion that we are undertaking a discounted cash flow " +
                        "(or intrinsic) valuation, making this instead a hybrid relative valuation.");

                startActivity(intent);

            }

        });



        textView.setText(
                        "In the WACC '(weighted verage cost of capital)' " +
                        "approach, we value the operating assets of " +
                        "a business by discounting he free cash flows " +
                        "to the firm (FCFF) by the cost of financing " +
                        "the assets (WACC or 'cost of capital'). " +
                        "FCFF is the cash flow efore debt payments, " +
                        "but after taxes and reinvestment needs. " +
                "It is estimated each year for a 'proforma' " +
                        "(or high-growth) period.  At the end of the " +
                        "proforma period, FCFF is assumed to grow at " +
                        "a constant rate forever, an assumption " +
                        "that allows us to bypass year-specfic " +
                        "estimates beyond that point in time, " +
                        "and a 'terminal value' (TV) is estimated. " +
                        "Both the proforma-period FCFF and TV are " +
                        "then discounted back to today and " +
                        "summed, to obtain the value of the" +
                "operating assets, also called the 'enterprise value' " +
        " or EV. To get from that value " +
                        "o the value of equity (E),we add back the cash" +
        "balance (C) of the firm and subtract the debt (D)" +
        "that is outstanding today: E= EV - D + C");




    }


}
