package com.example.finance.googlesheetsexample;

import android.content.Intent;
import android.os.Bundle;
import android.support.design.widget.NavigationView;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.MenuItem;
import android.view.View;
import android.widget.ListView;
import android.widget.PopupWindow;
import android.widget.TextView;

import com.example.finance.googlesheetsexample.androidlabs.gsheets1.MyArrayAdapter;
import com.example.finance.googlesheetsexample.androidlabs.gsheets1.MyDataModel;
import com.facebook.drawee.backends.pipeline.Fresco;

import java.util.ArrayList;

public class WACCDetailed extends AppCompatActivity {

    private ListView listView;
    private ArrayList<MyDataModel> list;
    private MyArrayAdapter adapter;
    private DrawerLayout mDrawerLayout;
    private TextView textView;
    private TextView WACCDescription;
    private TextView FCFFDescription;
    private TextView CostOfCapitalDescription;
    private TextView TerminalValueDescription;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.waccdetailed);

        Fresco.initialize(this);

        //!!!!!!!!!!!!!FORMAT THIS EVENTUALLY!!!!!!!!!!!!!!!!!!!!!
        //Below is repeat code from the MainPage, MainPage and Userlist use
        //the same code as below, see if there is a way to condense this

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        ActionBar actionbar = getSupportActionBar();
        //actionbar.setDisplayHomeAsUpEnabled(true);
        //actionbar.setHomeAsUpIndicator(R.drawable.baseline_menu_black_18dp);

        mDrawerLayout = findViewById(R.id.drawer_layout);

        textView = (TextView) this.findViewById(R.id.WACCTextView);


        WACCDescription = (TextView) this.findViewById(R.id.WACCDescription);
        WACCDescription.setText("What is WACC Method of Valuation?");

        WACCDescription.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(WACCDetailed.this, pdf_viewer.class));
                //Logic

            }

        });

        FCFFDescription = (TextView) this.findViewById(R.id.FCFFDescription);
        FCFFDescription.setText("What is Free Cash Flow to Firm (FCFF)?");

        FCFFDescription.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                PopUpWindow popUpWindow = new PopUpWindow();
                //TODO: look into setting text like above way
                Intent intent = new Intent(WACCDetailed.this, PopUpWindow.class);
                intent.putExtra("message", "FCFF is free cash flow to the firm.  It is" +
                        "the cash flow generated by the firm's operating assets," +
                        "net of taxes, after reinvestment needs have been met.  It is " +
                        "dervied using the pricniple that we should focus on the money " +
                        "that actually comes into and goes out of the firm, without" +
                        "reflecting the effects of debt financing.  It is defined as:" +
                        "\n\nFCFF = EBITx(1-t) + Depreciation - ∆NWC - Capex" +
                        "\n\nwhere EBIT is operating income, t is the tax rate, Depreciation" +
                        "is the non-cash charge that is added back, ∆NWC is change in operating" +
                        "net working capital (i.e., change in non-cash current assets minus" +
                        "change in non-debt current liabilities), and Capex is Capital" +
                        "Expenditure." +
                        "\n\nWe can think of Capex-Depreciation+∆NWC as the firm's net" +
                        "reinvestment needs." +
                        "\n\nSimply put, if FCFF is a positive number, it is the total cash" +
                        "flow that is available to service debt payments and cash flows" +
                        "to equity, including dividends and stock buybacks.  If " +
                        "negative, it represents new capital that has to be raised by the " +
                        "firm from either debt or equity.");

                //



                startActivity(intent);

            }

        });

        CostOfCapitalDescription = (TextView) this.findViewById(R.id.CostOfCapitalDescription);
        CostOfCapitalDescription.setText("What is Cost of Capital?");

        CostOfCapitalDescription.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(WACCDetailed.this, PopUpWindow.class));
                //Logic

            }

        });

        TerminalValueDescription = (TextView) this.findViewById(R.id.TerminalValueDescription);
        TerminalValueDescription.setText("What is Terminal Value?");

        TerminalValueDescription
                .setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(WACCDetailed.this, PopUpWindow.class));
                //Logic


            }

        });



        textView.setText(
                        "In the WACC '(weighted verage cost of capital)' " +
                        "approach, we value the operating assets of " +
                        "a business by discounting he free cash flows " +
                        "to the firm (FCFF) by the cost of financing " +
                        "the assets (WACC or 'cost of capital'). " +
                        "FCFF is the cash flow efore debt payments, " +
                        "but after taxes and reinvestment needs. " +
                "It is estimated each year for a 'proforma' " +
                        "(or high-growth) period.  At the end of the " +
                        "proforma period, FCFF is assumed to grow at " +
                        "a constant rate forever, an assumption " +
                        "that allows us to bypass year-specfic " +
                        "estimates beyond that point in time, " +
                        "and a 'terminal value' (TV) is estimated. " +
                        "Both the proforma-period FCFF and TV are " +
                        "then discounted back to today and " +
                        "summed, to obtain the value of the" +
                "operating assets, also called the 'enterprise value' " +
        " or EV. To get from that value " +
                        "o the value of equity (E),we add back the cash" +
        "balance (C) of the firm and subtract the debt (D)" +
        "that is outstanding today: E= EV - D + C");




    }


}
